name: eagleyeix
description: Eagleyeix the Dart library for sharper observations and smarter reactions
version: 0.3.0
homepage: https://github.com/flarebyte/eagleyeix
repository: https://github.com/flarebyte/eagleyeix
topics:
  - observer
environment:
  sdk: ^3.4.4
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
