name: eagleyeix
description: Eagleyeix the Dart library for sharper observations and smarter reactions
version: 0.3.0
homepage: https://github.com/flarebyte/eagleyeix
repository: https://github.com/flarebyte/eagleyeix
topics:
  - observer
  - metric
  - logger
  - privacy
environment:
  sdk: ^3.4.3
dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
